baseURL: ''
languageCode: en-us
title: Joel's Portfolio
theme: PaperMod

params:
    homeInfoParams:
    Title: "Hey, I’m Dan \U0001F44B"
    Content: I'm an enthusiastic data scientist currently working to assist in decarbonisation efforts.
    socialIcons:
    - name: github
        url: https://github.com/Danielwoodh
    - name: linkedin
        url: https://www.linkedin.com/in/daniel-woodhall/

menu:
    main:
    - identifier: home
        name: Home
        url: /
        weight: 10
    - identifier: posts
        name: Blog
        url: /posts/
        weight: 20
