baseURL: 'https://danielwoodh.github.io/'
languageCode: 'en-uk'
title: 'Daniel Woodhall'
theme: 'PaperMod'

params:
  defaultTheme: dark
  disableThemeToggle: true
  enableEmoji: true
  ShowCodeCopyButtons: true
  author: "Daniel Woodhall"

  homeInfoParams:
    Title: Hey, I'm Dan 👋
    Content:  I'm an enthusiastic data scientist currently working to improve decarbonisation efforts across the UK.

  socialIcons:
    - name: "GitHub"
      url: "https://github.com/Danielwoodh"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/daniel-woodhall/"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 1
    keys: ["title", "tags", "summary", "content"]

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: posts
      name: Blog
      url: /posts/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archive.md
      weight: 30
    - identifier: search
      name: Search
      url: /search.md
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON