baseURL: 'https://danielwoodh.github.io/'
languageCode: 'en-uk'
title: 'Daniel Woodhall'
theme: 'PaperMod'

params:
    defaultTheme: dark
    disableThemeToggle: true

    homeInfoParams:
        Title: Hey, I'm Dan wave
        Content:  I'm an enthusiastic data scientist currently working to improve decarbonisation efforts across the UK.

    # socialIcons:
    #     - name: "GitHub"
    #     url: "https://github.com/Danielwoodh"