baseURL = 'https://Danielwoodh.github.io/dw-website/'
languageCode = 'en-us'
title = 'D Woodhall Personal Website'
theme = 'PaperMod'

[params]
    author = "Daniel Woodhall"
    description = "A blog to share projects and facilitate continued learning."

    [[params.social]]
        icon = "github"
        name = "GitHub"
        url = "https://github.com/Danielwoodh"